version: '3' 
services:
 mysql:
   image: mysql:5.7
   ports:
    - "3306:3306"
   volumes:
    - ./db/mysql_init:/docker-entrypoint-initdb.d
    - ./db/mysql_data:/var/lib/mysql
    - ./my.cnf:/etc/mysql/conf.d/my.cnf
   environment:
    MYSQL_DATABASE: omcdb
    MYSQL_ROOT_PASSWORD: manager
    MYSQL_USER: ORACLEUSR2
    MYSQL_PASSWORD: oracle
   container_name: mysql

 tomcat:
   build: .
   ports:
     - 8080:8080
   volumes:
     - ./tomcat/log:/usr/local/tomcat/log
   container_name: tomcat
   links:
     - mysql

